Repository Amijakan/mochatto, pull requests merged in 2022-10, with the labels that each got.

#319 Ft 318 Create make command for debugging tests
  Makefile
  README.md
  client/package.json
  docker-compose.yaml
Labels: devops, high priority

#323 added network_mode: host for test-client containers
  README.md
  docker-compose.yaml
Labels: devops

#317 Added attachable process
  README.md
  docker-compose.yaml
  server/.vscode/launch.json
  server/package.json
Labels: devops

#237 Ft 164 Sidebar with user list
  client/package.json
  client/src/components/AvatarCanvas/AvatarDOM/index.tsx
  client/src/components/AvatarCanvas/AvatarDOM/style.scss
  client/src/components/AvatarCanvas/index.tsx
  client/src/components/Logo/style.scss
  client/src/components/Sidebar/ChatHistory/index.tsx
  client/src/components/Sidebar/SidebarBody/index.tsx
  client/src/components/Sidebar/SidebarHead/SidebarButton/index.tsx
  client/src/components/Sidebar/SidebarHead/index.tsx
  client/src/components/Sidebar/UserList/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Sidebar/style.scss
  client/src/components/index.ts
  client/src/constants/style.scss
  client/src/contexts/UserInfoContext.tsx
  client/src/pages/JoinPage/style.scss
  client/src/pages/RoomPage/index.tsx
  client/tsconfig.json
Labels: enhancement

#312 Ft 74 Room authentication
  README.md
  client/src/constants/style.scss
  client/src/contexts/SocketIOContext.tsx
  client/src/pages/HomePage/index.tsx
  client/src/pages/JoinPage/index.tsx
  client/src/pages/JoinPage/style.scss
  client/tests/base.spec.ts
  server/package.json
  server/src/index.ts
  server/yarn.lock
Labels: enhancement

#335 ft-334 Add password visibility toggle button
  client/src/constants/style.scss
  client/src/pages/JoinPage/index.tsx
  client/src/pages/JoinPage/style.scss
Labels: hacktoberfest, hacktoberfest-accepted
